### ISSUE TITLE
Any plans for extending playback speed to past 2x

### ISSUE THREAD

**Issue by j-koreth** [mymindstorm/bb-collab-speed-control#3]
The extension has been great to use, thank you for making it. Are there any plans to make it past 2x playback speed?

**Comment by mymindstorm** [comment]
Not at the moment, but it should be very easy for you to make your own build with custom speeds.

All you need to do is add the desired speed to this list:

https://github.com/mymindstorm/bb-collab-speed-control/blob/cb7c8c83f4ff0e57e412cfe36388ef27bfab24eb/src/content.ts#L100

I will consider adding settings to change the speed options.

**Comment by j-koreth** [comment]
That sounds good! I was planning on that or maybe making it a slider for the playback speed like VLC.
