### ISSUE TITLE
Popup closes itself on Large browser font size or above [Chrome]

### ISSUE THREAD

**Issue by TwentyPorts** [mymindstorm/bb-collab-speed-control#4]
The playback speed control no longer seems to work. Clicking the **1x** leaves it unchanged. I've tested this with multiple BB Collab recordings with the same result.

**Comment by mymindstorm** [comment]
I am currently using it without issues. Could you give me a link to the recording, your browser name and version, and any messages from your browser's console?

**Comment by TwentyPorts** [comment]
Unfortunately my school forbids me from sharing any recordings so I can't share the link. I'm using the latest version of Chrome (Version 93.0.4577.63), and I've tested it with all my other Chrome extensions disabled, and the issue persists. Here's the full console log:
![image](https://user-images.githubusercontent.com/70867864/132113708-91bab818-d743-453d-acb6-8c78f49e9a9e.png)

However, I also installed the extension on Firefox and it _did_ work there, so maybe it's a Chrome-only problem?

Sorry again, I know that if I could share the recording it would make it easier to debug.

**Comment by mymindstorm** [comment]
On Chromium 91.0.4472.164 and Collaborate v22.11.4-warmfix.4.1, I am unable to reproduce. Could you test with a fresh profile? That would be better than just disabling all extensions. What I'm curious about with the link is what subdomain is the recording on (e.g. it could be `us`, `us-lti`, `eu`).

If you'd like to investigate, the id of the popup menu is `speedControlContainer`. It should have the class `dropdown-pane is-open` when visible and `dropdown-pane` when hidden. Could Chrome be interpreting a double click and hiding the menu right after you open it? Does it work if you manually add the `is-open` class? https://github.com/mymindstorm/bb-collab-speed-control/blob/cb7c8c83f4ff0e57e412cfe36388ef27bfab24eb/src/content.ts#L80-L89

**Comment by TwentyPorts** [comment]
Okay, so it did work on a fresh profile!

The link's on the `us` subdomain and if I manually set the class to `dropdown-pane is-open`, this successfully opens the popup menu and lets me choose a speed.

The weird thing is that I still can't click to open the dropdown on either of my two existing user profiles, but it does work on a newly created one. It doesn't seem to be the fault of any of my extensions, at least. I added all my extensions to the new profile and it worked just fine.

When I click the playback speed the DOM shows the class being changed:
![image](https://user-images.githubusercontent.com/70867864/132136221-381a0e7d-129c-471f-8b92-1980e55bbed4.png)
But I don't actually see the change, it just stays as `class="dropdown-pane`, which sounds like the double-click problem you mentioned.

**Comment by mymindstorm** [comment]
It's probably something set in `chrome://flags` that is causing this, although that's too much trouble to narrow down.

So that's either a double click or the button isn't being properly recognized on line 87. Could you use a breakpoint in chrome or console.log and figure out the order of what's going on? Build instructions are in readme.

**Comment by TwentyPorts** [comment]
Ah, I believe I've found the cause. My font-size is set to Large. By default, it's Medium.

When you open the popup on Medium font size, you get:
![image](https://user-images.githubusercontent.com/70867864/132138081-221cf5c9-af44-4689-98b9-cbfd2be50d38.png)

But on Large font size, the dropdown is big enough that the 0.75x option overlaps with the speed button. (result of breakpoint on line 74)
![image](https://user-images.githubusercontent.com/70867864/132138225-9f8e738f-bb10-47a0-8195-8a7350c1c525.png)

So once I open the dropdown, the next block of code checks `var el = document.elementFromPoint(e.x, e.y);` I put a `console.log(el)` after this line and I get this output on Large font-size:
![image](https://user-images.githubusercontent.com/70867864/132138170-c7c5f7ba-e18b-42c9-bd10-8e13f9eb0fe0.png)

On Medium font-size it works as intended and instead outputs 
![image](https://user-images.githubusercontent.com/70867864/132138179-16b16efa-a34c-41a2-b072-2e800a0e5a9e.png)

Seems like the double-click thing you mentioned: first it opens the dropdown then it closes again. You should be able to replicate this by setting your font-size to Large or above.

**Comment by mymindstorm** [comment]
Thanks for the help with debugging, I've pushed a fix to the web store; it should be available in a few days. You can also load this version manually: [1.1.2.zip](https://github.com/mymindstorm/bb-collab-speed-control/files/7112292/1.1.2.zip)

**Comment by TwentyPorts** [comment]
Thank you for making this extension and keeping it up-to-date. It's a real life-saver for my efficiency. :)
